FROM oven/bun:1

WORKDIR /app/backend

COPY package*.json ./

COPY bun.lock ./

RUN bun install

COPY . .

RUN bunx prisma generate

ENV DATABASE_URL="" \
    JWT_SECRET=""

EXPOSE 3000

CMD [ "bun", "run", "dev"]