services:
    postgres:
      image: postgres
      container_name: postgres
      environment: 
        - POSTGRES_PASSWORD=mysecretpassword
      ports:
        - "5432:5432"
      networks:
        - kanban_project
      volumes:
        - postgres_data:/var/lib/postgresql/data


    frontend:
      build: 
        context: ../client/
        dockerfile: ../docker/Dockerfile.client
      container_name: kanban-client
      environment:
        VITE_BACKEND_URL: http://localhost:3000/api/v1/ 
      ports:
          - "4173:4173"
      depends_on:
          - backend


    backend:
      build:
        context: ../backend
        dockerfile: ../docker/Dockerfile.backend
      container_name: kanban-backend
      ports:
        - "3000:3000"
      environment:
        DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/postgres
        JWT_SECRET: supersecretjwt
      depends_on:
         - postgres
      networks:
         - kanban_project

networks:
    kanban_project:

volumes:
  postgres_data: