FROM oven/bun:1-alpine

WORKDIR /app/client

ARG VITE_BACKEND_URL
COPY package*.json ./
COPY bun.lock ./

RUN bun install

COPY . .

ENV VITE_BACKEND_URL=${VITE_BACKEND_URL}

RUN bun run build

EXPOSE 5173

CMD [ "bun", "run", "preview"]
